import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./layout/header";
import Footer from "./layout/footer";
import ScrollToTopButton from "./layout/scrollToTop";
import StoreProvider from "./storeProvider";
import BookAppointment from "./component/bookApointment";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Supreme Motor Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          {children}
          <ScrollToTopButton />
          <Footer />
          <BookAppointment />
        </StoreProvider>
      </body>
    </html>
  );
}
